apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-operator
rules:
  - apiGroups:
      - ""
    attributeRestrictions: null
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - integreatly.org
    attributeRestrictions: null
    resources:
      - grafanadashboards
      - grafanas
    verbs:
      - '*'