apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-clusterrole
roleRef:
  name: grafana-clusterrole
subjects:
  - kind: ServiceAccount
    name: grafana-operator
    namespace: application-monitoring
userNames:
  - system:serviceaccount:application-monitoring:grafana-operator
